#ifndef __PARSER_DATASTRUCTURE__
#define __PARSER_DATASTRUCTURE__
enum synerror///语法错误标签。 
{
	TYPELOST,TYPEWRONG,//类型 
	IDLOST,IDWRONG,//标识符 
	NUMLOST,NUMWRONG,//数组的长度 
	LITERALLOST,LITERALWRONG,//常量 
	COMMALOST,COMMAWRONG,//, 
	SEMICONLOST,SEMICONWRONG,//;
	ASSIGNLOST,ASSIGNWRONG,//=
	COLONLOST,COLONWRONG,//:
	STATEMENTLOST,STATEMENTWRONG,//语句
	LPARENLOST,LPARENWRONG,//(
	RPARENLOST,RPARENWRONG,//)
	LBRACKLOST,LBRACKWRONG,//[
	RBRACKLOST,PBRACKWRONG,//]
	LBRACELOST,LBRACEWRONG,//{
	RBRACELOST,RBRACEWRONG//}
};
#endif
